#!/usr/bin/env bash

# openssl rsa -in private.pem -out public.pem -outform PEM -pubout
mkdir -p keys

# openssl genrsa -des3 -out keys/mykey.pem 2048
openssl genrsa -out keys/mykey.pem 2048
chmod go-rw keys/mykey.pem
openssl rsa -in keys/mykey.pem -pubout -outform PEM -out keys/mykey.pub
ssh-keygen -y -f keys/mykey.pem > keys/ssh_mykey.pub

