#!/usr/bin/env bash

header="$(jq -M -c . jwt_sample_data/header_rs256.json | tr -d '\n' | base64 --wrap 0)"  
payload="$(jq -M -c . jwt_sample_data/payload.json | tr -d '\n' | base64 --wrap 0)"  

signature="$( echo -n "${header}.${payload}" \
  | openssl sha -sha256 -binary -sign keys/mykey.pem \
  | base64 --wrap 0)"

mkdir -p data

echo "${header}.${payload}.${signature}" \
  | tee data/jwt_rs256

echo "${signature}"   \
  | tee data/jwt_rs256_signature

echo "${header}.${payload}" \
  | tee data/jwt_payload


