#!/usr/bin/env bash

header="$(jq -M -c . data/header_rs256.json | tr -d '\n' | openssl enc -base64)"  
payload="$(jq -M -c . data/payload.json | tr -d '\n' | openssl enc -base64)"  

signature="$( echo -n "${header}.${payload}" \
  | openssl sha -sha256 -binary -sign keys/mykey.pem \
  | openssl enc -base64 )"

mkdir -p data

echo "${header}.${payload}.${signature}" \
  | tee data/jwt_rs256

echo "${signature}"   \
  | tee data/jwt_rs256_signature

echo "${header}.${payload}" \
  | tee data/jwt_payload


