#!/usr/bin/env bash

mkdir -p messages

MESSAGE="$@"
[[ -z "$MESSAGE" ]] && MESSAGE="hello world"
echo -n "$MESSAGE" \
  | openssl dgst -sha256 -sign keys/mykey.pem -out messages/message.hash.sign.txt


